---
- name: Set up development environment
  hosts: localhost
  tasks:
  - name: Update apt repository cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Install Vim
    ansible.builtin.apt:
      name: vim
      state: present

  - name: Install Fish
    ansible.builtin.apt:
      name: fish
      state: present

  - name: Install Tmux
    ansible.builtin.apt:
      name: tmux
      state: present

  - name: Create .vimrc file
    ansible.builtin.copy:
      content: |
        call plug#begin('~/.vim/plugged')
        Plug 'preservim/nerdtree'
        Plug 'vim-airline/vim-airline'
        Plug 'ycm-core/YouCompleteMe'
        call plug#end()
      dest: /root/.vimrc
      owner: root
      group: root
      mode: '0644'

  - name: Create config.fish file
    ansible.builtin.copy:
      content: |
        # Your Fish configuration here
      dest: /root/.config/fish/config.fish
      owner: root
      group: root
      mode: '0644'

  - name: Create .tmux.conf file
    ansible.builtin.copy:
      content: |
        set -g @plugin 'tmux-plugins/tmux-resurrect'
        run '~/.tmux/plugins/tpm/tpm'
      dest: /root/.tmux.conf
      owner: root
      group: root
      mode: '0644'

  - name: Install vim-plug
    ansible.builtin.shell:
      cmd: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  - name: Install tmux-resurrect
    ansible.builtin.git:
      repo: https://github.com/tmux-plugins/tmux-resurrect.git
      dest: ~/.tmux/plugins/tmux-resurrect
...
